server:
  port: 8084
  
spring:
  application:
     name: client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
      
logging:
  level:
    '[org.springframework.core.io.support]': DEBUG
    '[org.springframework.context.annotation]': DEBUG      